// src/initialData.ts

import { Product } from '../types'; // Import types for type checking

export const INITIAL_CATEGORIES: string[] = [
  'Electronics',
  'Food',
  'Clothing',
  'Books',
  'Tools',
  'Furniture',
  'Appliances',
  'Footwear',
  'Kitchenware',
  'Accessories'
];

export const INITIAL_PRODUCTS: Product[] = [
    {
        id: '1',
        name: 'Laptop',
        category: 'Electronics',
        price: 999.99,
        expirationDate: '2025-12-31',
        stock: 15,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '2',
        name: 'LG 3',
        category: 'Electronics',
        price: 200.99,
        expirationDate: '',
        stock: 15,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '3',
        name: 'Watermelon',
        category: 'Food',
        price: 1.2,
        expirationDate: '2025-3-20',
        stock: 50,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '4',
        name: 'Milk',
        category: 'Food',
        price: 1.5,
        expirationDate: '2025-12-31',
        stock: 15,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '5',
        name: 'T-shirt',
        category: 'Clothing',
        price: 9.99,
        expirationDate: '',
        stock: 20,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '6',
        name: 'React Book',
        category: 'Books',
        price: 19.99,
        expirationDate: '',
        stock: 10,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '7',
        name: 'Hammer',
        category: 'Tools',
        price: 12.99,
        expirationDate: '',
        stock: 5,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        id: '8',
        name: 'Smartphone',
        category: 'Electronics',
        price: 699.99,
        expirationDate: '2026-06-30',
        stock: 25,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '9',
        name: 'Table Lamp',
        category: 'Furniture',
        price: 49.99,
        expirationDate: '',
        stock: 30,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '10',
        name: 'Jeans',
        category: 'Clothing',
        price: 39.99,
        expirationDate: '',
        stock: 10,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '11',
        name: 'Coffee Maker',
        category: 'Appliances',
        price: 79.99,
        expirationDate: '',
        stock: 8,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '12',
        name: 'Microwave Oven',
        category: 'Appliances',
        price: 129.99,
        expirationDate: '',
        stock: 12,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '13',
        name: 'Gaming Mouse',
        category: 'Electronics',
        price: 49.99,
        expirationDate: '',
        stock: 20,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '14',
        name: 'Electric Kettle',
        category: 'Appliances',
        price: 29.99,
        expirationDate: '',
        stock: 15,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '15',
        name: 'Headphones',
        category: 'Electronics',
        price: 79.99,
        expirationDate: '',
        stock: 18,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '16',
        name: 'Running Shoes',
        category: 'Footwear',
        price: 59.99,
        expirationDate: '',
        stock: 10,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '17',
        name: 'Blender',
        category: 'Appliances',
        price: 39.99,
        expirationDate: '',
        stock: 7,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '18',
        name: 'Frying Pan',
        category: 'Kitchenware',
        price: 15.99,
        expirationDate: '',
        stock: 20,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '19',
        name: 'Backpack',
        category: 'Accessories',
        price: 29.99,
        expirationDate: '',
        stock: 15,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '20',
        name: 'Wrench Set',
        category: 'Tools',
        price: 25.99,
        expirationDate: '',
        stock: 5,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, 
      {
        id: '21',
        name: 'Sunglasses',
        category: 'Accessories',
        price: 19.99,
        expirationDate: '',
        stock: 30,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
];
